seeder:
 file: ./seeder/seeder.rb
 disabled: false
parsers:
 - page_type: products
   file: ./parsers/products.rb
   disabled: false
exporters:
 - file: ./exporters/products_json.yaml
   disabled: true
 - file: ./exporters/products_csv.yaml
   disabled: true
